version: "3"
services:

  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/runtime/nginxproxymanager/data:/data
      - /data/runtime/nginxproxymanager/letsencrypt:/etc/letsencrypt

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/runtime/portainer:/data

networks:
  proxy:
    external: true
