version: "3"
services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - portainer.data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - nginxproxymanager.data:/data
      - nginxproxymanager.letsencrypt:/etc/letsencrypt

volumes:
  portainer.data:
  nginxproxymanager.data:
  nginxproxymanager.letsencrypt:

networks:
  proxy:
    external: true
